### ISSUE TITLE
Wrong quote characters in setup_the_server.md

### ISSUE THREAD

**Issue by kmacdchap** [tiagofreire-pt/rpi_uputronics_stratum1_chrony#3]
Excellent project.  I did find a few typos in the file **setup_the_server.md**.  The sed command failed because the following lines contain backtick (grave accent) characters instead of single quote characters:

line 98
sudo sed -i `s/CPU_DEFAULT_GOVERNOR ...

line 105
sudo sed -i `/if ...

The gpsd.service failed to start as line 145
      DEVICES="/dev/ttyAMA0 /dev/pps0″
ends with a 'seconds' character (code 0x2033) in lieu of the double quote character.  I see you had corrected a similar issue with the adafruit project.

Apart from the typos there were a couple of other things I had problems with.  I did not need the the the parameter **dtparam=i2c_arm=on** in the [pi5] section of the **config.txt** file as it already exists near the top of the file as a comment.  You can manually uncomment the line or edit it via the **raspi-config** utility.

Finally I needed to add:
  sudo systemctl enable gpsd

I inserted it prior to
  sudo systemctl restart gpsd

This may be due to me inadvertently disabling gpsd.service while debugging it due to line 145 in **setup_the_server.md**.  I decided to leave it in as a precaution.

Even with these issues I found the setup easy to follow.  Well done.

**Comment by tiagofreire-pt** [comment]
Thanks, @kmacdchap .

Make sure you do not use the RAW .md file, and just copy through the browser rendered version.

**Comment by kmacdchap** [comment]
> Thanks, @kmacdchap .
> 
> Make sure you do not use the RAW .md file, and just copy through the browser rendered version.

I intentionally avoided the the rendered version due to past issues with formatted docs.  Oh well.

Thanks for the update.

**Comment by tiagofreire-pt** [comment]
Corrected: https://github.com/tiagofreire-pt/rpi_uputronics_stratum1_chrony/blob/main/steps/setup_the_server.md#setup-the-gpsd-daemon
