### ISSUE TITLE
chronyc not seeing time

### ISSUE THREAD

**Issue by MLWALK3R** [tiagofreire-pt/rpi_uputronics_stratum1_chrony#5]
Hi I've followed this guide twice and still get the same result no time in chronyc from the GPS hat. Just wondering if you'd have any ideas what could have been missed.

```
===============================================================================
#? GPS                           0   8     0     -     +0ns[   +0ns] +/-    0ns
#? PPS                           0   4     0     -     +0ns[   +0ns] +/-    0ns
#? kPPS                          0   4     0     -     +0ns[   +0ns] +/-    0ns
^? ntp2.wiktel.com               0   5   377     -     +0ns[   +0ns] +/-    0ns
^? swag.maxhost.io               0   5   377     -     +0ns[   +0ns] +/-    0ns
^* connected.by.freedominte>     2   5   377    56   +310us[ +309us] +/-   12ms
^- time.cloudflare.com           3   5   377    27  +2129us[+2129us] +/-   12ms
```
```

trying PPS source "/dev/pps0"
found PPS source "/dev/pps0"
ok, found 1 source(s), now start fetching data...
source 0 - assert 1731849446.001408482, sequence: 638 - clear  0.000000000, sequence: 0
source 0 - assert 1731849447.001396983, sequence: 639 - clear  0.000000000, sequence: 0
source 0 - assert 1731849448.001386187, sequence: 640 - clear  0.000000000, sequence: 0
```

**Comment by tiagofreire-pt** [comment]
Hi, @MLWALK3R .

run:

```
service gpsd status
```

And after that:

```gpsmon```

Post here your results.

Thanks.

**Comment by MLWALK3R** [comment]
```
/dev/ttyAMA0                  u-blox>
┌──────────────────────────────────────────────────────────────────────────────┐or":14}
│Time: 2024-11-17T14:31:44.000Z   Lat: 000 N   Lon:   000' W │ivated":"2024-11-17T14:31:29.434Z","native":0,"bps":115200,"parity":"N","stopbits":1,"cycle":1.00}]}
└───────────────────────────────── Cooked TPV ─────────────────────────────────┘false,"timing":false,"split24":false,"pps":true}
┌──────────────────────────────────────────────────────────────────────────────┐
│ GNRMC GNVTG GNGGA GNGSA GPGSV GLGSV GNGLL                                    │
└───────────────────────────────── Sentences ──────────────────────────────────┘
┌───────────────────────┌─────────────────────────┌────────────────────────────┐
│ SVID  PRN  Az El SN HU│Time:     143144.00      │Time:      143144.00        │
│GP 10   10 287 28 52  Y│Latitude:   000 N │Latitude:  000004       │
│GP 12   12 206 55 45  Y│Longitude: 00007 W │Longitude0000177      │
│GP 15   15 168 28 25  Y│Speed:    0.013          │Altitude:  30.1             │
│GP 17   17  50 27 39  Y│Course:                  │Quality:   1   Sats: 12     │
│GP 23   23 243 21 48  Y│Status:   A        FAA:A │HDOP:      0.77             │
│GP 24   24 110 83 43  Y│MagVar:                  │Geoid:     49.1             │
│GP 25   25 226 17 42  Y└───────── RMC ───────────└─────────── GGA ────────────┘
│GP 32   32 313 19 49  Y┌─────────────────────────┌────────────────────────────┐
│GL  6   70 249 62 36  Y│Mode: A3 Sats: 10 12 15 +│UTC:           RMS:         │
│GL  7   71 322 35 45  Y│DOP H=0.77 V=1.15 P=1.38 │MAJ:           MIN:         │
│GL  9   73 249 21 48  Y│TOFF:  0.049240136       │ORI:           LAT:         │
│GL 15   79  54 42 41  Y│PPS: N/A                 │LON:           ALT:         │or":14}
└───v──── GSV ──────────└────── GSA + PPS ────────└─────────── GST ────────────┘ivated":"2024-11-17T14:31:29.434Z","native":0,"bps":115200,"parity":"N","stopbits":1,"cycle":1.00}]}
(70) $GPGSV,3,2,10,15,28,168,26,17,27,050,38,23,21,243,48,24,83,110,42*71
(44) $GPGSV,3,3,10,25,17,226,42,32,19,313,49*7C
(70) $GLGSV,3,1,09,69,18,176,16,70,62,249,36,71,35,322,44,73,21,249,48*61
(68) $GLGSV,3,2,09,79,42,054,41,80,75,284,46,81,17,083,24,87,00,338,*62
(31) $GLGSV,3,3,09,88,20,028,40*50
(52) $GNGLL,5321.13038,N,00246.62179,W,143141.00,A,A*60
(68) $GNRMC,143142.00,A,5321.13037,N,00246.62178,W,0.022,,171124,,,A*74
(35) $GNVTG,,T,,M,0.022,N,0.040,K,A*39
(74) $GNGGA,143142.00,5321.13037,N,00246.62178,W,1,12,0.77,30.2,M,49.1,M,,*66
(58) $GNGSA,A,3,10,23,24,32,12,25,15,17,,,,,1.38,0.77,1.15*12
(56) $GNGSA,A,3,71,73,80,79,88,81,70,,,,,,1.38,0.77,1.15*19
(68) $GPGSV,3,1,10,02,04,000,45,10,28,287,52,12,55,206,45,13,07,142,*78
(70) $GPGSV,3,2,10,15,28,168,26,17,27,050,38,23,21,243,48,24,83,110,42*71
(44) $GPGSV,3,3,10,25,17,226,42,32,19,313,49*7C
(70) $GLGSV,3,1,09,69,18,176,18,70,62,249,36,71,35,322,44,73,21,249,48*6F
(68) $GLGSV,3,2,09,79,42,054,41,80,75,284,46,81,17,083,24,87,00,338,*62
(31) $GLGSV,3,3,09,88,20,028,41*51
(52) $GNGLL,5321.13037,N,00246.62178,W,143142.00,A,A*6D
(68) $GNRMC,143143.00,A,5321.13036,N,00246.62178,W,0.006,,171124,,,A*72
(35) $GNVTG,,T,,M,0.006,N,0.010,K,A*3A
(74) $GNGGA,143143.00,5321.13036,N,00246.62178,W,1,12,0.77,30.1,M,49.1,M,,*65
(58) $GNGSA,A,3,10,23,24,32,12,25,15,17,,,,,1.38,0.77,1.15*12
(56) $GNGSA,A,3,71,73,80,79,88,81,70,,,,,,1.38,0.77,1.15*19
(68) $GPGSV,3,1,11,02,04,000,45,10,28,287,52,12,55,206,45,13,07,142,*79
(68) $GPGSV,3,2,11,15,28,168,25,17,27,050,39,19,36,086,,23,21,243,48*7A
(57) $GPGSV,3,3,11,24,83,110,42,25,17,226,42,32,19,313,49*46
(70) $GLGSV,3,1,09,69,18,176,18,70,62,249,36,71,35,322,44,73,21,249,48*6F
(68) $GLGSV,3,2,09,79,42,054,41,80,75,284,46,81,17,083,23,87,00,338,*65
(31) $GLGSV,3,3,09,88,20,028,40*50
(52) $GNGLL,5321.13036,N,00246.62178,W,143143.00,A,A*6D
(68) $GNRMC,143144.00,A,5321.13034,N,00246.62177,W,0.013,,171124,,,A*7C
(35) $GNVTG,,T,,M,0.013,N,0.024,K,A*39
(74) $GNGGA,143144.00,5321.13034,N,00246.62177,W,1,12,0.77,30.1,M,49.1,M,,*6F
(58) $GNGSA,A,3,10,23,24,32,12,25,15,17,,,,,1.38,0.77,1.15*12
(56) $GNGSA,A,3,71,73,80,79,88,81,70,,,,,,1.38,0.77,1.15*19
(68) $GPGSV,3,1,11,02,04,000,45,10,28,287,52,12,55,206,45,13,07,142,*79
(70) $GPGSV,3,2,11,15,28,168,25,17,27,050,39,19,36,086,28,23,21,243,48*70
(57) $GPGSV,3,3,11,24,83,110,43,25,17,226,42,32,19,313,49*47
(70) $GLGSV,3,1,09,69,18,176,18,70,62,249,36,71,35,322,45,73,21,249,48*6E
(68) $GLGSV,3,2,09,79,42,054,41,80,75,284,46,81,17,083,23,87,00,338,*65
(31) $GLGSV,3,3,09,88,20,028,41*51
(52) $GNGLL,5321.13034,N,00246.62177,W,143144.00,A,A*67


```



```
● gpsd.service - GPS (Global Positioning System) Daemon
     Loaded: loaded (/lib/systemd/system/gpsd.service; disabled; preset: enabled)
     Active: active (running) since Sun 2024-11-17 14:31:27 GMT; 58s ago
TriggeredBy: ● gpsd.socket
    Process: 853 ExecStart=/usr/sbin/gpsd $GPSD_OPTIONS $OPTIONS $DEVICES (code=exited, status=0/SUCCESS)
   Main PID: 854 (gpsd)
      Tasks: 1 (limit: 9580)
        CPU: 52ms
     CGroup: /system.slice/gpsd.service
             └─854 /usr/sbin/gpsd /dev/ttyAMA0 /dev/pps0″ GPSD_OPTIONS=--nowait --badtime --passive --speed 115200

Nov 17 14:31:27 pi systemd[1]: Starting gpsd.service - GPS (Global Positioning System) Daemon...
Nov 17 14:31:27 pi systemd[1]: Started gpsd.service - GPS (Global Positioning System) Daemon.
Nov 17 14:31:29 pi gpsd[854]: gpsd:ERROR: SER: device open of /dev/pps0\xe2\x80\xb3 failed: No such file or directory - retrying read-only
Nov 17 14:31:29 pi gpsd[854]: gpsd:ERROR: SER: read-only device open of /dev/pps0\xe2\x80\xb3 failed: No such file or directory
Nov 17 14:31:29 pi gpsd[854]: gpsd:ERROR: /dev/pps0\xe2\x80\xb3: device activation failed, freeing device.
Nov 17 14:31:29 pi gpsd[854]: gpsd:ERROR: SER: device open of GPSD_OPTIONS=--nowait failed: No such file or directory - retrying read-only
Nov 17 14:31:29 pi gpsd[854]: gpsd:ERROR: SER: read-only device open of GPSD_OPTIONS=--nowait failed: No such file or directory
Nov 17 14:31:29 pi gpsd[854]: gpsd:ERROR: GPSD_OPTIONS=--nowait: device activation failed, freeing device.
```
restarted it again.
```
● gpsd.service - GPS (Global Positioning System) Daemon
     Loaded: loaded (/lib/systemd/system/gpsd.service; disabled; preset: enabled)
     Active: active (running) since Sun 2024-11-17 14:32:54 GMT; 5s ago
TriggeredBy: ● gpsd.socket
    Process: 1415 ExecStart=/usr/sbin/gpsd $GPSD_OPTIONS $OPTIONS $DEVICES (code=exited, status=0/SUCCESS)
   Main PID: 1416 (gpsd)
      Tasks: 1 (limit: 9580)
        CPU: 3ms
     CGroup: /system.slice/gpsd.service
             └─1416 /usr/sbin/gpsd /dev/ttyAMA0 /dev/pps0″ GPSD_OPTIONS=--nowait --badtime --passive --speed 115200

Nov 17 14:32:54 pi systemd[1]: Starting gpsd.service - GPS (Global Positioning System) Daemon...
Nov 17 14:32:54 pi systemd[1]: Started gpsd.service - GPS (Global Positioning System) Daemon.

```

**Comment by masterdka** [comment]
Hello @tiagofreire-pt,

also seeing the same problem. 

chronyc soureces
#? GPS                           0   8     0     -     +0ns[   +0ns] +/-    0ns
#? PPS                           0   4     0     -     +0ns[   +0ns] +/-    0ns
#? kPPS                          0   4     0     -     +0ns[   +0ns] +/-    0ns
^* time-a-wwv.nist.gov           1   5   377     3    +13us[  -49us] +/- 6348us
^+ time-a-b.nist.gov             1   5   377     2   -855us[ -855us] +/- 7290us

gpsd service

`justin@time:~ $ sudo systemctl status gpsd.service
● gpsd.service - GPS (Global Positioning System) Daemon
     Loaded: loaded (/lib/systemd/system/gpsd.service; enabled; preset: enabled)
     Active: active (running) since Fri 2024-12-06 23:39:14 MST; 5min ago
TriggeredBy: ● gpsd.socket
    Process: 884 ExecStart=/usr/sbin/gpsd $GPSD_OPTIONS $OPTIONS $DEVICES (code=exited, status=0/SUCCESS)
   Main PID: 885 (gpsd)
      Tasks: 1 (limit: 767)
        CPU: 18ms
     CGroup: /system.slice/gpsd.service
             └─885 /usr/sbin/gpsd /dev/ttyAMA0 /dev/pps0″ GPSD_OPTIONS=--nowait --badtime --passive --speed 115200

Dec 06 23:39:14 time systemd[1]: Starting gpsd.service - GPS (Global Positioning System) Daemon...
Dec 06 23:39:14 time systemd[1]: Started gpsd.service - GPS (Global Positioning System) Daemon.`


gpsmon detials
`/dev/ttyAMA0                  u-blox>
lqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqkor":14}
xTime: 2024-12-07T06:37:43.000Z   Lat: 39 33.689010' N   Lon: 104 47.994900' W xivated":"2024-12-07T06:37:30.447Z","native":0,"bps":115200,"parity":"N","stopbits":1,"cycle":1.00
mqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqq Cooked TPV qqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqj
lqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqkfalse,"timing":false,"split24":false,"pps":true}
x GNRMC GNVTG GNGGA GNGSA GPGSV GLGSV GNGLL                                    x
mqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqq Sentences qqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqj
lqqqqqqqqqqqqqqqqqqqqqqqlqqqqqqqqqqqqqqqqqqqqqqqqqlqqqqqqqqqqqqqqqqqqqqqqqqqqqqk
x SVID  PRN  Az El SN HUxTime:     063743.00      xTime:      063743.00        x
xGP  5    5  87 78 42  YxLatitude:   3933.68901 N xLatitude:  3933.68901       x
xGP 11   11  65 28 28  YxLongitude: 10447.99490 W xLongitude: 10447.99490      x
xGP 12   12 184 22 32  YxSpeed:    0.025          xAltitude:  1765.8           x
xGP 13   13 127 15 25  YxCourse:                  xQuality:   2   Sats: 12     x
xGP 15   15 163 15 33  YxStatus:   A        FAA:D xHDOP:      0.62             x
xGP 18   18 272 25 34  YxMagVar:                  xGeoid:     -21.8            x
xGP 20   20  49 45 36  Ymqqqqqqqqq RMC qqqqqqqqqqqmqqqqqqqqqqq GGA qqqqqqqqqqqqj
xGP 25   25 226 41 36  Ylqqqqqqqqqqqqqqqqqqqqqqqqqlqqqqqqqqqqqqqqqqqqqqqqqqqqqqk
xGP 29   29 319 62 39  YxMode: A3 Sats: 5 11 12 + xUTC:           RMS:         x
xSB133   46 215 38 33  YxDOP H=0.62 V=1.19 P=1.34 xMAJ:           MIN:         x
xSB135   48 210 40 30  YxTOFF:  0.060884149       xORI:           LAT:         x
xGL  1   65 175  9 28  YxPPS: N/A                 xLON:           ALT:         xor":14}
mqqqvqqqq GSV qqqqqqqqqqmqqqqqq GSA + PPS qqqqqqqqmqqqqqqqqqqq GST qqqqqqqqqqqqjivated":"2024-12-07T06:37:30.447Z","native":0,"bps":115200,"parity":"N","stopbits":1,"cycle":1.00
(70) $GPGSV,4,3,13,25,41,226,36,26,09,321,21,29,62,319,39,46,38,215,33*72
(31) $GPGSV,4,4,13,48,40,210,30*43
(68) $GLGSV,3,1,12,65,09,175,28,70,03,020,,71,38,052,35,72,46,124,40*69
(66) $GLGSV,3,2,12,76,02,200,,77,25,238,22,78,26,304,31,79,01,346,*68
(63) $GLGSV,3,3,12,86,30,072,31,87,56,009,19,88,23,299,33,,,,42*54
(52) $GNGLL,3933.68901,N,10447.99496,W,063741.00,A,D*66
(68) $GNRMC,063742.00,A,3933.68901,N,10447.99493,W,0.025,,071224,,,D*7C
(35) $GNVTG,,T,,M,0.025,N,0.046,K,D*3D
(81) $GNGGA,063742.00,3933.68901,N,10447.99493,W,2,12,0.62,1765.6,M,-21.8,M,,0000*41
(64) $GNGSA,A,3,05,20,15,29,18,25,12,46,11,13,48,,1.34,0.62,1.19*1E
(58) $GNGSA,A,3,71,72,87,77,78,86,88,65,,,,,1.34,0.62,1.19*19
(70) $GPGSV,4,1,13,05,78,087,42,11,28,065,28,12,22,184,32,13,15,127,25*74
(68) $GPGSV,4,2,13,15,15,163,33,18,25,272,34,20,45,049,36,23,02,216,*7A
(70) $GPGSV,4,3,13,25,41,226,36,26,09,321,21,29,62,319,39,46,38,215,33*72
(31) $GPGSV,4,4,13,48,40,210,30*43
(68) $GLGSV,3,1,12,65,09,175,28,70,03,020,,71,38,052,35,72,46,124,40*69
(66) $GLGSV,3,2,12,76,02,200,,77,25,238,21,78,26,304,31,79,01,346,*6B
(63) $GLGSV,3,3,12,86,30,072,31,87,56,009,19,88,23,299,34,,,,42*53
(52) $GNGLL,3933.68901,N,10447.99493,W,063742.00,A,D*60
(68) $GNRMC,063743.00,A,3933.68901,N,10447.99490,W,0.025,,071224,,,D*7E
(35) $GNVTG,,T,,M,0.025,N,0.047,K,D*3C
(81) $GNGGA,063743.00,3933.68901,N,10447.99490,W,2,12,0.62,1765.8,M,-21.8,M,,0000*4D
(64) $GNGSA,A,3,05,20,15,29,18,25,12,46,11,13,48,,1.34,0.62,1.19*1E
(58) $GNGSA,A,3,71,72,87,77,78,86,88,65,,,,,1.34,0.62,1.19*19
(70) $GPGSV,4,1,13,05,78,087,42,11,28,065,28,12,22,184,32,13,15,127,25*74
(68) $GPGSV,4,2,13,15,15,163,33,18,25,272,34,20,45,049,36,23,02,216,*7A
(70) $GPGSV,4,3,13,25,41,226,36,26,09,321,21,29,62,319,39,46,38,215,33*72
(31) $GPGSV,4,4,13,48,40,210,30*43
(68) $GLGSV,3,1,12,65,09,175,28,70,03,020,,71,38,052,35,72,46,124,40*69
(66) $GLGSV,3,2,12,76,02,200,,77,25,238,22,78,26,304,31,79,01,346,*68
(63) $GLGSV,3,3,12,86,30,072,32,87,56,009,19,88,23,299,34,,,,42*50
(52) $GNGLL,3933.68901,N,10447.99490,W,063743.00,A,D*62
`

**Comment by cmiller123456** [comment]
Agreed @masterdka - I think we are all running into the same issue. Hoping to see if this can be resolved @tiagofreire-pt 

**chronyc sources -v**

#? GPS                           0   8     0     -     +0ns[   +0ns] +/-    0ns
#? PPS                           0   4     0     -     +0ns[   +0ns] +/-    0ns
#? kPPS                          0   4     0     -     +0ns[   +0ns] +/-    0ns
^+ c-73-234-118-31.hsd1.nh.>     2   5   377    24    -24us[  -24us] +/-   65ms
^+ time3.lshiy.com               2   5   377    21   +110us[ +110us] +/-   65ms
^+ ntp1.wiktel.com               2   5   377    10   +165us[ +165us] +/-   65ms
^+ h96-60-160-227.stgrut.br>     2   5   377    34  -1784ns[-1784ns] +/-   65ms
^+ europa.ellipse.net            2   5   377    41    -25us[  -25us] +/-   64ms
^+ time.circlevps.net            2   5   377    66  +1614ns[+1614ns] +/-   64ms
^+ arm1.maxhost.io               2   5   377    93   +117us[ +117us] +/-   63ms
^* 65-100-46-164.dia.static>     2   5   377   148   +723ns[+4044ns] +/-   63ms
^+ 23.155.40.38                  2   5   377    30  +5316ns[+5316ns] +/-   65ms
^+ time-h.den.codehof.net        2   5   377    91    -17us[  -17us] +/-   64ms
^+ tick.chi1.ntfo.org            2   5   377    49    +54us[  +54us] +/-   64ms
^+ swag.maxhost.io               2   5   377    35    -30us[  -30us] +/-   65ms


**journalctl -u gpsd.service --no-pager**

Dec 08 00:26:04 bigben systemd[1]: Starting gpsd.service - GPS (Global Positioning System) Daemon...
Dec 08 00:26:04 bigben systemd[1]: Started gpsd.service - GPS (Global Positioning System) Daemon.
Dec 08 00:26:09 bigben gpsd[844]: **gpsd:ERROR: SER: device open of /dev/pps0\xe2\x80\xb3 failed: No such file or directory - retrying read-only**
Dec 08 00:26:09 bigben gpsd[844]: **gpsd:ERROR: SER: read-only device open of /dev/pps0\xe2\x80\xb3 failed: No such file or directory**
Dec 08 00:26:09 bigben gpsd[844]: **gpsd:ERROR: /dev/pps0\xe2\x80\xb3: device activation failed, freeing device.**
Dec 08 00:26:09 bigben gpsd[844]: **gpsd:ERROR: SER: device open of #GPSD_OPTIONS=--nowait failed: No such file or directory - retrying read-only**
Dec 08 00:26:09 bigben gpsd[844]: **gpsd:ERROR: SER: read-only device open of #GPSD_OPTIONS=--nowait failed: No such file or directory**
Dec 08 00:26:09 bigben gpsd[844]: **gpsd:ERROR: #GPSD_OPTIONS=--nowait: device activation failed, freeing device**.
Dec 08 00:30:02 bigben systemd[1]: Stopping gpsd.service - GPS (Global Positioning System) Daemon...
Dec 08 00:30:02 bigben systemd[1]: gpsd.service: Deactivated successfully.
Dec 08 00:30:02 bigben systemd[1]: Stopped gpsd.service - GPS (Global Positioning System) Daemon.

**Comment by masterdka** [comment]
I can see if I don't use SHM PPS device will work.  There seems to be an issue with gpsd or chronyd and SHM reading or writing.  I also did a build of the latest gpsd 3.25 same symtoms.  Even tried raspbian bullseye with the same results.  Now I know the guide was for a Pi5 but the same should apply just omitting the Pi5 items in config.txt.

**Comment by cmiller123456** [comment]
Yeah, I agree - I disabled SHM and PPS works fine for me as well and was considered "current best" consistently. Glad you mentioned Bullseye, I was going to try the same... even flirted with the idea of Trixie, but that's probably a step in the wrong direction based on my past experiences. At least it feels like the scope of what's off may be closing.

**Comment by tiagofreire-pt** [comment]
Make sure the configuration on the: https://github.com/tiagofreire-pt/rpi_uputronics_stratum1_chrony/blob/main/steps/setup_the_server.md#setup-the-gpsd-daemon

Has the correct text, wthout strange chars: 

`
gpsd:ERROR: SER: device open of /dev/pps0\xe2\x80\xb3 failed: No such file or directory - retrying read-only
`

**Comment by MLWALK3R** [comment]
my is exactly that in the document and still doesn't work.

**Comment by cmiller123456** [comment]
Thank you @tiagofreire-pt This appears to have done the trick! I picked up some odd characters in the copy-paste, as shown below:

Original:
root@bigben:~# cat -A /etc/default/gpsd
START_DAEMON="true"$
USBAUTO="false"$
DEVICES="/dev/ttyAMA0 /dev/pps0M-bM-^@M-3$
GPSD_OPTIONS="--nowait --badtime --passive --speed 115200"$

Corrected:
root@bigben:~# cat -A /etc/default/gpsd
START_DAEMON="true"$
USBAUTO="false"$
DEVICES="/dev/ttyAMA0 /dev/pps0"$
GPSD_OPTIONS="--nowait --badtime --passive --speed 115200"$

Corrected that in the file, and I'm getting better results. Haven't dropped the ?/unusable flag yet on GPS but will see if that clears up on it's own or not - I'm guessing it should.

MS Name/IP address         Stratum Poll Reach LastRx Last sample
=================================================
#? GPS                           0   8     7   144    -11ms[  -11ms] +/-  200ms
#* PPS                           0   4   377    10    +65ns[ +732ns] +/-  192ns
#+ kPPS                          0   4   377    10    +65ns[  +65ns] +/-  192ns
^- tick.srs1.ntfo.org            3   5   377    54  -5064us[-5063us] +/-   66ms
^- 74.208.117.38                 3   5   377    23  -5078us[-5077us] +/-   66ms
^- b09-07.sysnet.ucsd.edu        3   5   377    87  -5043us[-5043us] +/-   65ms
^- us-central-1.clearnet.pw      3   5   377    22  -5065us[-5065us] +/-   66ms
^- us-east-2.clearnet.pw         3   5   377    16  -5080us[-5080us] +/-   66ms
^- 65-100-46-166.dia.static>     3   5   377    18  -5064us[-5063us] +/-   66ms
^- 198.71.50.75                  3   5   377    17  -5052us[-5051us] +/-   66ms
^- 149.248.12.167.vultruser>     3   5   377    49  -5067us[-5067us] +/-   66ms
