### ISSUE TITLE
Error: 506 Cannot talk to daemon - Advanced system tuning

### ISSUE THREAD

**Issue by cmiller123456** [tiagofreire-pt/rpi_uputronics_stratum1_chrony#7]
Hello @tiagofreire-pt 

Followed the instructions for **Enable support for PTP Hardware Clock (PHC) on the Ethernet chip** but I constantly receive a **506 Cannot talk to daemon** error when chronyc sources -v.

Any suggestions on how I can troubleshoot this? Thank you.

**Comment by tiagofreire-pt** [comment]
Make sure the chrony service is running without configuration errors:

```
sudo systemctl status chronyd
```
